export const FORM_CHANNEL = 'FORM_CHANNEL';
export const GET_CHANNELS = 'GET_CHANNELS';
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const FORM_VALIDATION = 'FORM_VALIDATION';
export const CURRENT_CHANNEL = 'CURRENT_CHANNEL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';


export const MESSAGES_CHANNEL = 'MESSAGES_CHANNEL';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_VALIDATION = 'MESSAGE_VALIDATION';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const MESSAGE_STATE = 'MESSAGE_STATE';
export const CURRENT_MESSAGE = 'CURRENT_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';